language: php
php:
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  allow_failures:
      - php: hhvm

env:
  matrix:
    - LOWEST_DEPS="" TEST_DEPS=""
    - LOWEST_DEPS="--prefer-lowest" TEST_DEPS="tests/Sabre/"

services:
  - mysql
  - postgresql

sudo: false

before_script:
  - mysql -e 'create database sabredav_test'
  - psql -c 'create database sabredav_test' -U postgres
  - phpenv config-rm xdebug.ini; true
  #  - composer self-update
  - composer update --prefer-dist $LOWEST_DEPS

script:
  - ./bin/phpunit --configuration tests/phpunit.xml.dist $TEST_DEPS
  - ./bin/sabre-cs-fixer fix lib/ --dry-run --diff

cache:
  directories:
    - $HOME/.composer/cache
