language: php
sudo: required
dist: xenial
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3snapshot

env:
  global:
    - SABRE_MYSQLUSER="root"
    - SABRE_MYSQLPASS=""
    - SABRE_MYSQLDSN="mysql:host=127.0.0.1;dbname=sabredav_test"
  matrix:
    - LOWEST_DEPS="" TEST_DEPS="" WITH_COVERAGE="--coverage-clover=coverage.xml"
    - LOWEST_DEPS="--prefer-lowest" TEST_DEPS="tests/Sabre/" $WITH_COVERAGE=""

services:
  - mysql
  - postgresql


before_script:
#  - mysql -u root -h 127.0.0.1 sabredav_test -e 'SELECT VERSION();'
#- mysql -u root -h 127.0.0.1 -e 'create database sabredav_test'
  - psql -c "create database sabredav_test" -U postgres
  - psql -c "create user sabredav with PASSWORD 'sabredav';GRANT ALL PRIVILEGES ON DATABASE sabredav_test TO sabredav" -U postgres
  - composer update --prefer-dist $LOWEST_DEPS

addons:
  apt:
    packages:
      - libzip4
  postgresql: "9.5"

script:
  - ./bin/phpunit --verbose --configuration tests/phpunit.xml.dist $WITH_COVERAGE $TEST_DEPS

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.composer/cache
